language: c
sudo: false

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

git:
  depth: false
  quiet: true

env:
  global:
    - PRETTYNAME="Adafruit Arcada Library"

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit Unified Sensor"
   - arduino --install-library "Adafruit NeoPixel"
   - arduino --install-library "Adafruit QSPI"
   - arduino --install-library "Adafruit GFX Library"
   - arduino --install-library "Adafruit ST7735 and ST7789 Library"

script:
   - build_arcada_platforms

after_success:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
