name: Arduino Library CI

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["pybadge", "pygamer", "pyportal",
	                   "hallowing_m4", "hallowing_m0",
                           "cpb", "cpx_ada", "pyportal_titano"]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install WiFi & Audio
    - uses: actions/checkout@v2
      with:
         repository: adafruit/WiFiNINA
         path: /home/runner/Arduino/libraries/WiFiNINA
    - uses: actions/checkout@v2
      with:
         repository: adafruit/Audio
         path: /home/runner/Arduino/libraries/Audio

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

  clang_and_doxy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit Arcada Library"
      run: bash ci/doxy_gen_and_deploy.sh

